### ISSUE TITLE
Missing assets?

### ISSUE THREAD

**Issue by katopz** [developit/preact-redux-example#1]
refer to https://github.com/developit/preact-redux-example/blob/master/package.json#L10
```
"prebuild": "mkdir -p build && ncp src/assets build/assets",
```
It should be `src/assets` somewhere?

**Comment by developit** [comment]
@katopz Apologies, I let this languish a bit. Just published a new version that looks and works much better, and fixes the issues you mentioned.

**Comment by katopz** [comment]
@developit No need to apologies. I'm just curios.
BTW your work is awesome! Appreciated it :+1:

**Comment by developit** [comment]
I'm Canadian, we apologize as a form of hello haha. Thanks :)
