### ISSUE TITLE
Redundant dependencies?

### ISSUE THREAD

**Issue by pinn3** [developit/preact-redux-example#2]
Might have missed some but, if I'm not mistaking, the following packages are redundant.
Not sure if you left them there for boiler purposes though

[babel-preset-es2015@package.json:27](https://github.com/developit/preact-redux-example/blob/master/package.json#L27)
Since you only use es2015-minimal

[preact-compat@package.json:53](https://github.com/developit/preact-redux-example/blob/master/package.json#L53) and [react@package.json:56](https://github.com/developit/preact-redux-example/blob/master/package.json#L56)
Because you never seem to use anything from the `react` package

[preact-router@package.json:54](https://github.com/developit/preact-redux-example/blob/master/package.json#L54)
Never used

Also, kind of off topic, regarding the last one; I've tried to implement redux in my own preact app with `react-redux` and `preact-router`, but the `Provider` component is complaining about its children, which are the `Router` component with its children:

```
invariant.js:38Uncaught Invariant Violation: onlyChild must be passed a children with exactly one child.
    invariant @ invariant.js:38
    onlyChild @ onlyChild.js:29
    render @ Provider.js:53
    hook @ preact.js:65
    renderComponent @ preact.js:379
    createComponentFromVNode @ preact.js:44
    8buildComponentFromVNode @ preact.js:435
    diff @ preact.js:226
    render @ preact.js:478
    80../config/routes @ index.js:24
    s @ _prelude.js:1
    e @ _prelude.js:1
    (anonymous function) @ _prelude.js:1
```
Any clue?

**Comment by katopz** [comment]
I'm curios too and also get that error when I try to add undo/redo too. @developit any hint please?

**Comment by developit** [comment]
Will look into this asap.  In React a single child is not wrapped in an array, which preact-compat attempts to emulate.

**Comment by developit** [comment]
Ah - I forgot to close this out when I switched the project to [preact-redux](https://git.io/preact-redux).  That fixed the unnecessary dependencies.  The minimal preset is required as I mentioned above, so it looks like this can be closed!

**Comment by abeaclark** [comment]
Does preact-redux fix this problem? Having the same issue

> Provider component is complaining about its children, which are the Router component with its children

Thanks.

**Comment by pinn3** [comment]
Yup, preact-redux takes care of it

**Comment by developit** [comment]
Awesome, thanks guys!
